group: longvid-reasoning-eval_v2_5sec
task:
  - longvid-reasoning-eval_v2_5sec_block_counting
  - longvid-reasoning-eval_v2_5sec_bulb
  - longvid-reasoning-eval_v2_5sec_hidden_dice_roll
  - longvid-reasoning-eval_v2_5sec_hockey_own_goal
  - longvid-reasoning-eval_v2_5sec_hockey_score
  - longvid-reasoning-eval_v2_5sec_make_coffee
  - longvid-reasoning-eval_v2_5sec_memory_sliding_puzzle
  - longvid-reasoning-eval_v2_5sec_morse
  - longvid-reasoning-eval_v2_5sec_opaque
  - longvid-reasoning-eval_v2_5sec_rhythm_game
  - longvid-reasoning-eval_v2_5sec_ring_toss
  - longvid-reasoning-eval_v2_5sec_shell_game
  - longvid-reasoning-eval_v2_5sec_shell_game_rotate
  - longvid-reasoning-eval_v2_5sec_sugar_new
  - longvid-reasoning-eval_v2_5sec_tighten_untighten
  - longvid-reasoning-eval_v2_5sec_tilt_box
