task: longvid-reasoning-eval_v2_5sec_memory_sliding_puzzle
process_docs: !function lmms_eval.tasks.longvid_reasoning_eval_v2_task_utils.process_memory_sliding_puzzle_docs
include: _default_template_yaml
