task: longvid-reasoning-eval_v2_5sec_ring_toss_counting_physics
process_docs: !function lmms_eval.tasks.longvid_reasoning_eval_v2_task_utils.process_ring_toss_counting_physics_docs
include: _default_template_yaml
