group: longvid-reasoning-eval_1min
task:
  - longvid-reasoning-eval_1min_block_counting
  - longvid-reasoning-eval_1min_hidden_dice_roll
  - longvid-reasoning-eval_1min_make_coffee
  - longvid-reasoning-eval_1min_memory_sliding_puzzle
  - longvid-reasoning-eval_1min_opaque
  - longvid-reasoning-eval_1min_rhythm_game
  - longvid-reasoning-eval_1min_shell_game
  - longvid-reasoning-eval_1min_shell_game_rotate
  - longvid-reasoning-eval_1min_tighten_untighten
  - longvid-reasoning-eval_1min_tilt_box
