dataset_path: json
class: !function utils.VSTATTask
dataset_kwargs:
  data_files:
    test: data/vstat/vstat_qa_clean.json
task: longvid-reasoning-eval_vista
test_split: test
output_type: generate_until
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
process_docs: !function utils.process_docs
process_results: !function utils.process_results
metric_list:
  - metric: Numeric_MRA
    aggregation: !function utils.aggregate_mean
    higher_is_better: true
  - metric: MCQ_ACC
    aggregation: !function utils.aggregate_mean
    higher_is_better: true
  - metric: ALL_Score_avg
    aggregation: !function utils.aggregate_mean
    higher_is_better: true
generation_kwargs:
  max_new_tokens: 16384
  temperature: 0
  do_sample: false
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    mcq_post_prompt: "Do not response anything other than a single letter from the given choices!"
    na_post_prompt: "Do not response anything other than a single number!"
metadata:
  version: 0.0
